#!/usr/bin/env bash
# gen-did.sh — regenerate candid/backend.did, the PUBLISHED Candid interface of
# the MULTI/DEX backend. Run it after changing the backend's public method
# surface, and commit the result.
#
# Why a committed copy when the live canister already exposes candid:service?
#   - It's the versioned, reviewable stability contract (additive-only within a
#     major apiVersion — see MM_API_VERSION / getMarketSpecs), diffable in PRs.
#   - Bot authors + tooling get the interface without a live canister to query.
#   - The deployed canister ALSO serves it as PUBLIC metadata (mops.toml passes
#     --public-metadata candid:service), so ic_describe_api etc. fetch it live.
#
# Candid carries SIGNATURES, not SEMANTICS. For the non-obvious behavior (sealed/
# staged matching, integer money @1e8, poll-for-fill, the dead-man switch) call
# the getApiDoc() query on the canister — the header below points there too.
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

# `mops generate candid` extracts the interface directly from the Motoko
# source WITHOUT compiling wasm (needs ic-mops >= 2.19; the old
# `icp build` + copy-from-.mops/.build two-step did a full build just to
# read the interface). Output path is mops.toml's [canisters.backend].candid
# — an intermediate, gitignored; the published copy is what THIS script
# writes below. Verified byte-identical to the icp-build route (2026-07-31).
mops generate candid backend >/dev/null
SRC="src/backend/backend.did"
[ -f "$SRC" ] || { echo "gen-did: $SRC not produced by 'mops generate candid backend'" >&2; exit 1; }

mkdir -p candid
{
  echo "// ─────────────────────────────────────────────────────────────────────"
  echo "// MULTI/DEX backend — PUBLISHED Candid interface (method signatures + types)."
  echo "//"
  echo "// GENERATED by scripts/gen-did.sh — do NOT edit by hand; regenerate after"
  echo "// any change to the public method surface, then commit."
  echo "//"
  echo "// Stability: ADDITIVE-ONLY within a major apiVersion (see getMarketSpecs)."
  echo "// Candid gives you the shapes, not the behavior: call getApiDoc() on the"
  echo "// canister for the semantics (staged matching, integer money @1e8, poll-"
  echo "// for-fill, the dead-man switch, fees/levels)."
  echo "// ─────────────────────────────────────────────────────────────────────"
  echo ""
  cat "$SRC"
} > candid/backend.did

echo "gen-did: wrote candid/backend.did ($(wc -l < candid/backend.did | tr -d ' ') lines)"
