#!/usr/bin/env bash
# gen-did.sh — regenerate candid/backend.did, the PUBLISHED Candid interface of
# the MULTI/DEX backend. Run it after changing the backend's public method
# surface, and commit the result.
#
# Why a committed copy when the live canister already exposes candid:service?
#   - It's the versioned, reviewable stability contract (additive-only within a
#     major apiVersion — see MM_API_VERSION / getMarketSpecs), diffable in PRs.
#   - Bot authors + tooling get the interface without a live canister to query.
#   - The deployed canister ALSO serves it as PUBLIC metadata (mops.toml passes
#     --public-metadata candid:service), so ic_describe_api etc. fetch it live.
#
# Candid carries SIGNATURES, not SEMANTICS. For the non-obvious behavior (sealed/
# staged matching, integer money @1e8, poll-for-fill, the dead-man switch) call
# the getApiDoc() query on the canister — the header below points there too.
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

# Extraction goes through scripts/lib/candid.sh, the SAME helper
# lint-ratchet.sh verifies this file with. That shared path is the point: a
# byte-equality gate whose writer and reader are different tools can drift
# between them, and this one did — the ratchet used `moc --idl` while this
# script used `mops generate candid`, which additionally needs ic-mops >= 2.19
# and so failed outright on a machine running 2.13.2 while the check verifying
# its output ran fine.
#
# It writes src/backend/backend.did too: mops.toml declares that path as
# [canisters.backend].candid and `mops build` treats it as a compat-check
# INPUT, so a build fails without it. Gitignored — an intermediate; the
# PUBLISHED copy is what this script assembles below.
# shellcheck source=scripts/lib/candid.sh
. "$(dirname "$0")/lib/candid.sh"
SRC="src/backend/backend.did"
mdx_emit_candid "$SRC" || { echo "gen-did: could not extract the interface" >&2; exit 1; }

mkdir -p candid
{
  echo "// ─────────────────────────────────────────────────────────────────────"
  echo "// MULTI/DEX backend — PUBLISHED Candid interface (method signatures + types)."
  echo "//"
  echo "// GENERATED by scripts/gen-did.sh — do NOT edit by hand; regenerate after"
  echo "// any change to the public method surface, then commit."
  echo "//"
  echo "// Stability: ADDITIVE-ONLY within a major apiVersion (see getMarketSpecs)."
  echo "// Candid gives you the shapes, not the behavior: call getApiDoc() on the"
  echo "// canister for the semantics (staged matching, integer money @1e8, poll-"
  echo "// for-fill, the dead-man switch, fees/levels)."
  echo "// ─────────────────────────────────────────────────────────────────────"
  echo ""
  cat "$SRC"
} > candid/backend.did

echo "gen-did: wrote candid/backend.did ($(wc -l < candid/backend.did | tr -d ' ') lines)"
